name: Ultimate Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  GRADLE_OPTS: "-Xmx4g -Dorg.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -Dorg.gradle.daemon=false"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: false
      
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # ⚡ خطوة الصاروخ: تفعيل الكاش لتسريع البناء Pub & Gradle لتقليل الوقت
      - name: Cache Flutter & Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.pub-cache
          key: ${{ runner.os }}-flutter-gradle-${{ hashFiles('**/pubspec.yaml', '**/build.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-flutter-gradle-
          
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true # تسريع محرك فلاتر نفسه
      - name: Build APK & Force Path
        env:
          GRADLE_OPTS: "-Xmx4g -Dorg.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -Dorg.gradle.daemon=false"
        run: |
          flutter config --no-enable-web
          flutter clean
          flutter pub get
          flutter build apk --debug
          
          # 🎯 قوة نظام لينكس: البحث الشامل من جذور حاوية GitHub عن الـ APK المفقود ونقله
          mkdir -p my_output_apk
          find /home/runner/work/ -name "*.apk" -exec cp {} my_output_apk/ \;
          
          echo "=== الملفات التي تم العثور عليها وقنصها ==="
          ls -la my_output_apk/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: final-app
          path: my_output_apk/*.apk
